#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-deckarep-golang-set
Version  : 1f0f4ff8d3fbef9328522993ce71c35890f67554
Release  : 6
URL      : https://github.com/deckarep/golang-set/archive/1f0f4ff8d3fbef9328522993ce71c35890f67554.tar.gz
Source0  : https://github.com/deckarep/golang-set/archive/1f0f4ff8d3fbef9328522993ce71c35890f67554.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : go

%description
[![Build Status](https://travis-ci.org/deckarep/golang-set.png?branch=master)](https://travis-ci.org/deckarep/golang-set)
[![GoDoc](https://godoc.org/github.com/deckarep/golang-set?status.png)](http://godoc.org/github.com/deckarep/golang-set)

%prep
%setup -q -n golang-set-1f0f4ff8d3fbef9328522993ce71c35890f67554

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/deckarep/golang-set"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/deckarep/golang-set

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/deckarep/golang-set/bench_test.go
/usr/lib/golang/src/github.com/deckarep/golang-set/set.go
/usr/lib/golang/src/github.com/deckarep/golang-set/set_test.go
/usr/lib/golang/src/github.com/deckarep/golang-set/threadsafe.go
/usr/lib/golang/src/github.com/deckarep/golang-set/threadsafe_test.go
/usr/lib/golang/src/github.com/deckarep/golang-set/threadunsafe.go
